#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define MAX_CMD_LEN 256
#define MAX_NUM_ARGS 64

extern char **environ;

char **split_string(char *str, char *delim) {
	    char **result = malloc(MAX_NUM_ARGS * sizeof(char *));
	        int i = 0;
		    char *token = strtok(str, delim);
		        while (token != NULL) {
				        result[i++] = token;
					        token = strtok(NULL, delim);
						    }
			    result[i] = NULL;
			        return result;
}

char *search_path(char *cmd) {
	    char *path = getenv("PATH");
	        char *path_copy = strdup(path);
		    char *dir = strtok(path_copy, ":");

		        while (dir != NULL) {
				        char *cmd_path = malloc(strlen(dir) + strlen(cmd) + 2);
					        strcpy(cmd_path, dir);
						        strcat(cmd_path, "/");
							        strcat(cmd_path, cmd);

								        if (access(cmd_path, F_OK) != -1) {
										            free(path_copy);
											                return cmd_path;
													        }

									        free(cmd_path);
										        dir = strtok(NULL, ":");
											    }

			    free(path_copy);
			        return NULL;
}

int process_cmd(char *cmd) {
	    // Split command into arguments
	    //     char **argv = split_string(cmd, " ");
	    //
	    //         // Check if command is "exit", "env", "setenv", "unsetenv", or "cd"
	    //             if (strcmp(argv[0], "exit") == 0) {
	    //                     if (argv[1] != NULL) {
	    //                                 int status = atoi(argv[1]);
	    //                                             exit(status);
	    //                                                     } else {
	    //                                                                 exit(0);
	    //                                                                         }
	    //                                                                             } else if (strcmp(argv[0], "env") == 0) {
	    //                                                                                     for (char **env = environ; *env != NULL; ++env) {
	    //                                                                                                 printf("%s\n", *env);
	    //                                                                                                         }
	    //                                                                                                                 return 0;
	    //                                                                                                                     } else if (strcmp(argv[0], "setenv") == 0) {
	    //                                                                                                                             if (argv[1] != NULL && argv[2] != NULL) {
	    //                                                                                                                                         if (setenv(argv[1], argv[2], 1) != 0) {
	    //                                                                                                                                                         perror("Error setting environment variable");
	    //                                                                                                                                                                         return 1;
	    //                                                                                                                                                                                     }
	    //                                                                                                                                                                                             } else {
	    //                                                                                                                                                                                                         fprintf(stderr, "Usage: setenv VARIABLE VALUE\n");
	    //                                                                                                                                                                                                                     return 1;
	    //                                                                                                                                                                                                                             }
	    //                                                                                                                                                                                                                                     return 0;
	    //                                                                                                                                                                                                                                         } else if (strcmp(argv[0], "unsetenv") == 0) {
	    //                                                                                                                                                                                                                                                 if (argv[1] != NULL) {
	    //                                                                                                                                                                                                                                                             if (unsetenv(argv[1]) != 0) {
	    //                                                                                                                                                                                                                                                                             perror("Error unsetting environment variable");
	    //                                                                                                                                                                                                                                                                                             return 1;
	    //                                                                                                                                                                                                                                                                                                         }
	    //                                                                                                                                                                                                                                                                                                                 } else {
	    //                                                                                                                                                                                                                                                                                                                             fprintf(stderr, "Usage: unsetenv VARIABLE\n");
	    //                                                                                                                                                                                                                                                                                                                                         return 1;
	    //                                                                                                                                                                                                                                                                                                                                                 }
	    //                                                                                                                                                                                                                                                                                                                                                         return 0;
	    //                                                                                                                                                                                                                                                                                                                                                             } else if (strcmp(argv[0], "cd") == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                     char *dir = argv[1];
	    //                                                                                                                                                                                                                                                                                                                                                                             if (dir == NULL) {
	    //                                                                                                                                                                                                                                                                                                                                                                                         dir = getenv("HOME");
	    //                                                                                                                                                                                                                                                                                                                                                                                                 } else if (strcmp(dir, "-") == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                             dir = getenv("OLDPWD");
	    //                                                                                                                                                                                                                                                                                                                                                                                                                     }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                             if (chdir(dir) != 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                         perror("Error changing directory");
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                     return 1;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                         setenv("OLDPWD", getenv("PWD"), 1);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     char cwd[MAX_CMD_LEN];
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 getcwd(cwd, sizeof(cwd));
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             setenv("PWD", cwd, 1);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return 0;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Search for command in PATH
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 char *cmd_path = search_path(argv[0]);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (cmd_path != NULL) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     int pid = fork();
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (pid == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (execve(cmd_path, argv, environ) == -1) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     perror("Error executing command");
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         exit(1);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     int status;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     waitpid(pid, &status, 0);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     free(cmd_path);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return WEXITSTATUS(status);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     printf("%s: command not found\n", argv[0]);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return 127;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return 0;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
	    //
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 int main() {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     char cmd[MAX_CMD_LEN];
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         while (1) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 printf("$ ");
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (fgets(cmd, sizeof(cmd), stdin) == NULL) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     printf("\n");
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 exit(0);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 cmd[strlen(cmd) - 1] = '\0';  // remove newline at the end
	    //
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Split input line into commands
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 char **cmds = split_string(cmd, ";");
	    //
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Process each command
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 int status = 0;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (int i = 0; cmds[i] != NULL; ++i) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     char *cmd = cmds[i];
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 char *next_cmd = cmds[i + 1];
	    //
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (next_cmd != NULL) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             char *sep = strchr(next_cmd, ' ');
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (sep != NULL) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 *sep = '\0';
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ++sep;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         while (*sep == ' ') ++sep;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cmds[i + 1] = sep;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
	    //
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (strcmp(next_cmd, "&&") == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (status == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         status = process_cmd(cmd);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else if (strcmp(next_cmd, "||") == 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (status != 0) {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         status = process_cmd(cmd);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 status = process_cmd(cmd);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } else {
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             status = process_cmd(cmd);
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return 0;
	    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
	    //
